import type { StyleSpecification } from 'maplibre-gl';
import {
    cnBoundaryLineOk,
    cnCountryLabelOk,
    cnRegionLabelFeatures,
    notCnNationalCapital,
    notCnRegionStateLabel,
} from './mapCnBoundaryPolicy';

/** OSM 路径：优先中文标注，其次本地名与通用 name */
const nameField: any = ['coalesce', ['get', 'name:zh'], ['get', 'name:zh-Hans'], ['get', 'name:nonlatin'], ['get', 'name']];
const nameWithLatin: any = [
    'case',
    ['any', ['has', 'name:zh'], ['has', 'name:zh-Hans']],
    ['coalesce', ['get', 'name:zh'], ['get', 'name:zh-Hans']],
    ['case', ['has', 'name:nonlatin'],
        ['concat', ['get', 'name:nonlatin'], '\n', ['get', 'name:latin']],
        ['get', 'name'],
    ],
];

const C = {
    parchment:  '#E8D5B5',
    parchDark:  '#DED0B5',
    water:      '#C2CFC8',
    waterLine:  '#A8BAB2',
    waterText:  '#5B7570',
    roadCase:   '#8B7B62',
    roadFill:   '#D8CCAE',
    motorCase:  '#7A6548',
    motorFill:  '#CCC1A0',
    roadSubtle: '#A09380',
    boundaryA:  '#6B5B4F',
    boundaryB:  '#8B7B6B',
    ink:        '#3D2B1F',
    inkLight:   '#5C4A3E',
    halo:       '#E8D5B5',
    building:   '#D8CBAF',
    park:       '#D6CEAC',
};

const serif = 'Noto Sans Regular';
const serifBold = 'Noto Sans Bold';
const serifItalic = 'Noto Sans Italic';

export const antiqueStyle: StyleSpecification = {
    version: 8,
    name: 'antique-bridge-map',
    sources: {
        openmaptiles: {
            type: 'vector',
            url: 'https://tiles.openfreemap.org/planet',
        },
        cnRegionLabels: {
            type: 'geojson',
            data: {
                type: 'FeatureCollection',
                features: cnRegionLabelFeatures,
            },
        },
    },
    sprite: 'https://tiles.openfreemap.org/sprites/ofm_f384/ofm',
    glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
    layers: [
        /* ---- background ---- */
        {
            id: 'background',
            type: 'background',
            paint: { 'background-color': C.parchment },
        },

        /* ---- landuse / landcover ---- */
        {
            id: 'park',
            type: 'fill',
            source: 'openmaptiles',
            'source-layer': 'park',
            filter: ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
            paint: { 'fill-color': C.park, 'fill-opacity': 0.5 },
        },
        {
            id: 'landuse_residential',
            type: 'fill',
            source: 'openmaptiles',
            'source-layer': 'landuse',
            maxzoom: 16,
            filter: ['all',
                ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
                ['==', ['get', 'class'], 'residential'],
            ],
            paint: {
                'fill-color': C.parchDark,
                'fill-opacity': ['interpolate', ['exponential', 0.6], ['zoom'], 8, 0.6, 9, 0.4],
            },
        },

        /* ---- water ---- */
        {
            id: 'water',
            type: 'fill',
            source: 'openmaptiles',
            'source-layer': 'water',
            filter: ['all',
                ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
                ['!=', ['get', 'brunnel'], 'tunnel'],
            ],
            paint: { 'fill-antialias': true, 'fill-color': C.water },
        },
        {
            id: 'waterway',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'waterway',
            filter: ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
            paint: {
                'line-color': C.waterLine,
                'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0.5, 10, 1.5, 14, 3],
            },
        },

        /* ---- buildings (high zoom) ---- */
        {
            id: 'building',
            type: 'fill',
            source: 'openmaptiles',
            'source-layer': 'building',
            minzoom: 13,
            paint: {
                'fill-antialias': true,
                'fill-color': C.building,
                'fill-outline-color': C.roadCase,
            },
        },

        /* ---- roads ---- */
        {
            id: 'highway_minor',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            minzoom: 8,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['match', ['get', 'class'], ['minor', 'service', 'track'], true, false],
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
                'line-color': C.roadSubtle,
                'line-opacity': 0.7,
                'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 13, 1, 20, 12],
            },
        },
        {
            id: 'highway_major_casing',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            minzoom: 11,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
            ],
            layout: { 'line-cap': 'butt', 'line-join': 'miter' },
            paint: {
                'line-color': C.roadCase,
                'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 10, 3, 20, 23],
            },
        },
        {
            id: 'highway_major_inner',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            minzoom: 11,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
                'line-color': C.roadFill,
                'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 10, 2, 20, 20],
            },
        },
        {
            id: 'highway_major_subtle',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            maxzoom: 11,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: { 'line-color': C.roadSubtle, 'line-width': 2, 'line-opacity': 0.7 },
        },
        {
            id: 'highway_motorway_casing',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            minzoom: 6,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['==', ['get', 'class'], 'motorway'],
            ],
            layout: { 'line-cap': 'butt', 'line-join': 'miter' },
            paint: {
                'line-color': C.motorCase,
                'line-opacity': 1,
                'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 5.8, 0, 6, 3, 20, 40],
            },
        },
        {
            id: 'highway_motorway_inner',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            minzoom: 6,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['==', ['get', 'class'], 'motorway'],
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
                'line-color': C.motorFill,
                'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 4, 2, 6, 1.3, 20, 30],
            },
        },
        {
            id: 'highway_motorway_subtle',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'transportation',
            maxzoom: 6,
            filter: ['all',
                ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
                ['==', ['get', 'class'], 'motorway'],
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
                'line-color': C.roadSubtle,
                'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 4, 2, 6, 1.3],
                'line-opacity': 0.7,
            },
        },

        /* ---- boundaries ---- */
        {
            id: 'boundary_3',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'boundary',
            minzoom: 3,
            filter: ['all',
                ['>=', ['get', 'admin_level'], 3],
                ['<=', ['get', 'admin_level'], 6],
                ['!=', ['get', 'maritime'], 1],
                cnBoundaryLineOk,
            ],
            paint: {
                'line-color': C.boundaryB,
                'line-dasharray': [3, 2],
                'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 7, 1, 11, 2],
            },
        },
        {
            id: 'boundary_2',
            type: 'line',
            source: 'openmaptiles',
            'source-layer': 'boundary',
            filter: ['all',
                ['==', ['get', 'admin_level'], 2],
                ['!=', ['get', 'maritime'], 1],
                cnBoundaryLineOk,
            ],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
                'line-color': C.boundaryA,
                'line-opacity': ['interpolate', ['linear'], ['zoom'], 0, 0.4, 4, 1],
                'line-width': ['interpolate', ['linear'], ['zoom'], 3, 1, 5, 1.5, 12, 3],
            },
        },

        /* ---- labels: water ---- */
        {
            id: 'waterway_label',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'waterway',
            minzoom: 10,
            filter: ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
            layout: {
                'symbol-placement': 'line',
                'symbol-spacing': 350,
                'text-field': nameField,
                'text-font': [serifItalic],
                'text-letter-spacing': 0.2,
                'text-max-width': 5,
                'text-size': 13,
            },
            paint: {
                'text-color': C.waterText,
                'text-halo-color': C.halo,
                'text-halo-width': 1.5,
            },
        },
        {
            id: 'water_name_point',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'water_name',
            filter: ['match', ['geometry-type'], ['MultiPoint', 'Point'], true, false],
            layout: {
                'text-field': nameField,
                'text-font': [serifItalic],
                'text-letter-spacing': 0.2,
                'text-max-width': 5,
                'text-size': ['interpolate', ['linear'], ['zoom'], 0, 10, 8, 14],
            },
            paint: {
                'text-color': C.waterText,
                'text-halo-color': C.halo,
                'text-halo-width': 1.5,
            },
        },

        /* ---- labels: roads ---- */
        {
            id: 'highway_name_major',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'transportation_name',
            minzoom: 12.2,
            filter: ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary', 'trunk'], true, false],
            layout: {
                'symbol-placement': 'line',
                'text-field': nameField,
                'text-font': [serif],
                'text-rotation-alignment': 'map',
                'text-size': ['interpolate', ['linear'], ['zoom'], 13, 11, 14, 12],
            },
            paint: {
                'text-color': C.inkLight,
                'text-halo-blur': 0.5,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },

        /* ---- labels: places ---- */
        {
            id: 'label_other',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 8,
            filter: ['match', ['get', 'class'], ['city', 'continent', 'country', 'state', 'town', 'village'], false, true],
            layout: {
                'text-field': nameField,
                'text-font': [serifItalic],
                'text-letter-spacing': 0.1,
                'text-max-width': 9,
                'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 12, 10],
            },
            paint: {
                'text-color': C.inkLight,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_village',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 9,
            filter: ['==', ['get', 'class'], 'village'],
            layout: {
                'icon-allow-overlap': true,
                'icon-image': ['step', ['zoom'], 'circle_11_black', 10, ''],
                'icon-optional': false,
                'icon-size': 0.15,
                'text-anchor': 'bottom',
                'text-field': nameField,
                'text-font': [serif],
                'text-max-width': 8,
                'text-size': ['interpolate', ['exponential', 1.2], ['zoom'], 7, 10, 11, 12],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_town',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 6,
            filter: ['==', ['get', 'class'], 'town'],
            layout: {
                'icon-allow-overlap': true,
                'icon-image': ['step', ['zoom'], 'circle_11_black', 10, ''],
                'icon-optional': false,
                'icon-size': 0.2,
                'text-anchor': 'bottom',
                'text-field': nameField,
                'text-font': [serif],
                'text-max-width': 8,
                'text-size': ['interpolate', ['exponential', 1.2], ['zoom'], 7, 12, 11, 14],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_cn_region',
            type: 'symbol',
            source: 'cnRegionLabels',
            minzoom: 4,
            maxzoom: 9,
            layout: {
                'text-field': ['get', 'name'],
                'text-font': [serifItalic],
                'text-letter-spacing': 0.15,
                'text-max-width': 8,
                'text-size': ['interpolate', ['linear'], ['zoom'], 4, 10, 7, 14],
            },
            paint: {
                'text-color': C.inkLight,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_state',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 4,
            maxzoom: 8,
            filter: ['all', ['==', ['get', 'class'], 'state'], notCnRegionStateLabel],
            layout: {
                'text-field': nameField,
                'text-font': [serifItalic],
                'text-letter-spacing': 0.15,
                'text-max-width': 9,
                'text-size': ['interpolate', ['linear'], ['zoom'], 4, 9, 8, 14],
            },
            paint: {
                'text-color': C.inkLight,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_city',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 3,
            filter: ['all', ['==', ['get', 'class'], 'city'], ['!=', ['get', 'capital'], 2]],
            layout: {
                'icon-allow-overlap': true,
                'icon-image': ['step', ['zoom'], 'circle_11_black', 9, ''],
                'icon-optional': false,
                'icon-size': 0.35,
                'text-anchor': 'bottom',
                'text-field': nameWithLatin,
                'text-font': [serif],
                'text-max-width': 8,
                'text-offset': [0, -0.1],
                'text-size': ['interpolate', ['exponential', 1.2], ['zoom'], 4, 11, 7, 13, 11, 18],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_city_capital',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 3,
            filter: ['all', ['==', ['get', 'class'], 'city'], ['==', ['get', 'capital'], 2], notCnNationalCapital],
            layout: {
                'icon-allow-overlap': true,
                'icon-image': ['step', ['zoom'], 'circle_11_black', 9, ''],
                'icon-optional': false,
                'icon-size': 0.45,
                'text-anchor': 'bottom',
                'text-field': nameWithLatin,
                'text-font': [serifBold],
                'text-max-width': 8,
                'text-offset': [0, -0.2],
                'text-size': ['interpolate', ['exponential', 1.2], ['zoom'], 4, 12, 7, 14, 11, 20],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_country_other',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            minzoom: 2,
            maxzoom: 9,
            filter: ['all', cnCountryLabelOk, ['>=', ['get', 'rank'], 3]],
            layout: {
                'text-field': nameWithLatin,
                'text-font': [serifBold],
                'text-max-width': 6.25,
                'text-size': ['interpolate', ['linear'], ['zoom'], 3, 9, 7, 17],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
        {
            id: 'label_country_major',
            type: 'symbol',
            source: 'openmaptiles',
            'source-layer': 'place',
            maxzoom: 9,
            filter: ['all', cnCountryLabelOk, ['<=', ['get', 'rank'], 2]],
            layout: {
                'text-field': nameWithLatin,
                'text-font': [serifBold],
                'text-max-width': 6.25,
                'text-size': ['interpolate', ['linear'], ['zoom'], 1, 10, 4, 18],
            },
            paint: {
                'text-color': C.ink,
                'text-halo-blur': 1,
                'text-halo-color': C.halo,
                'text-halo-width': 1,
            },
        },
    ] as any[],
};
